### ISSUE TITLE
Closing the last tab increments the tab's name by 1

### ISSUE THREAD

**Issue by PigsPlayingPoker** [skst/CalculateX#11]
Closing the last tab increases the tab number by 1

**Comment by skst** [comment]
So, closing the last tab should result in a single tab named "Workspace1" with no entries?

**Comment by PigsPlayingPoker** [comment]
Yes

________________________________

**Comment by skst** [comment]
Fixed by 77adfe0cb6b9b5ed4546656eb8065a2cacd8cab4

**Comment by skst** [comment]
Fixed again by b91ffd07264ce5561a294ddcb834d9486244e18e
