### ISSUE TITLE
Ignore group separators (e.g., ',' in U.S.) when evaluating expression

### ISSUE THREAD

**Issue by PigsPlayingPoker** [skst/CalculateX#2]
Ignore commas ~~and dollar signs~~ for basic functions for copy pasting please. Or perhaps a toggle feature for ignoring these characters?

**Comment by skst** [comment]
I split this into two issues because the fixes will be separate.

**Comment by skst** [comment]
Commit 1905136f2c02961ec92323fe2b0054857180dc12 removes group separators from pasted text.

it's impossible to correctly remove group separators from function arguments because group separators also separate function arguments. (Example: `MAX(1,234,567)`)
